language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
before_install: 
  - npm install -g grunt-cli
  - npm install -g bower
install: 
  - npm install 
  - bower install
before_script:
  - grunt build
